#!/bin/sh

if [ $# -eq 0 ]
then
  echo "efaconky: missing or wrong parameter"
  echo "Try 'efaconky --help' for more information."
elif [ $1 = "preview" ]
then
  exec "/home/$USER/.efaconky/src/preview.py"
elif [ $1 = "add" ]
then
  exec "/home/$USER/.efaconky/src/add.py"
elif [ $1 = "remove" ]
then
  exec "/home/$USER/.efaconky/src/remove.py"
elif [ $1 = "start" ]
then
  exec conky -c /home/$USER/.conkyrc_departure_monitor
elif [ $1 = "--help" ]
then
  echo "Usage: efaconky [add/remove/preview/start]"
  echo "        or efaconky --help to show this page"
else
  echo "efaconky: missing or wrong parameter"
  echo "Try 'efaconky --help' for more information."
fi
